# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1234034432);
user_pref("app.update.lastUpdateTime.background-update-timer", 1234034431);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1234034431);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1234034432);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1234034432);
user_pref("browser.ctrlTab.mostRecentlyUsed", true);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 0);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.5");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.warnOnQuit", false);
user_pref("browser.warnOnRestart", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.enabledItems", "langpack-en-GB@firefox-3.0.ubuntu.com:3.0.3,{dc572301-7619-498c-a57d-39143191b318}:0.3.7.3,ubufox@ubuntu.com:0.6,langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.5");
user_pref("extensions.lastAppVersion", "3.0.5");
user_pref("extensions.tabmix.closeOtherMenu", false);
user_pref("extensions.tabmix.closeTabMenu", false);
user_pref("extensions.tabmix.copyTabUrlMenu", false);
user_pref("extensions.tabmix.duplicateMenu", false);
user_pref("extensions.tabmix.hideAllTabsButton", true);
user_pref("extensions.tabmix.hideTabbar", 2);
user_pref("extensions.tabmix.newTabButton", false);
user_pref("extensions.tabmix.newTabMenu", false);
user_pref("extensions.tabmix.protectTabMenu", false);
user_pref("extensions.tabmix.reloadAllMenu", false);
user_pref("extensions.tabmix.reloadTabMenu", false);
user_pref("extensions.tabmix.selected_sub_tab1", 0);
user_pref("extensions.tabmix.selected_sub_tab2", 0);
user_pref("extensions.tabmix.selected_sub_tab3", 0);
user_pref("extensions.tabmix.selected_sub_tab4", 0);
user_pref("extensions.tabmix.selected_sub_tab5", 0);
user_pref("extensions.tabmix.selected_sub_tab6", 0);
user_pref("extensions.tabmix.selected_tab", 0);
user_pref("extensions.tabmix.sessions.crashRecovery", false);
user_pref("extensions.tabmix.sessions.onClose", 2);
user_pref("extensions.tabmix.sessions.onStart.askifempty", false);
user_pref("extensions.tabmix.sessions.onStart.sessionpath", "");
user_pref("extensions.tabmix.sessions.restore.saveoverwrite", false);
user_pref("extensions.tabmix.sessions.save.history", false);
user_pref("extensions.tabmix.sessions.save.locked", false);
user_pref("extensions.tabmix.sessions.save.permissions", false);
user_pref("extensions.tabmix.sessions.save.protected", false);
user_pref("extensions.tabmix.sessions.save.scrollposition", false);
user_pref("extensions.tabmix.sessions.save.selectedtab", false);
user_pref("extensions.tabmix.undoCloseListMenu", false);
user_pref("extensions.tabmix.undoCloseTabMenu", false);
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.http", "localhost");
user_pref("network.proxy.http_port", 4444);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.type", 1);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1236626434);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
